issue #2 - add RolandTheFrank profile page
BuidlGuidl/batch8.buidlguidl.com pull request #15
Opened 2024-08-11 16:25 UTC by RafaelCaso

## Description

add profile page using NextPage component

Your ENS/address: 0xd1B41bE30F980315b8A6b754754aAa299C7abea2

2024-08-13 08:19 UTC, phipsae requested changes
Thanks for the PR, @RafaelCaso!

I really like your design.

Here are a few minor suggestions for potential improvements.

2024-08-13 08:19 UTC, phipsae commented on packages/nextjs/app/builders/0xd1B41bE30F980315b8A6b754754aAa299C7abea2/page.tsx
> +    <div className="w-96 px-6 py-6  text-center bg-gray-800 rounded-lg lg:mt-0 xl:px-10">
It would be great if you could center your personal page box both horizontally and vertically on the page.

2024-08-13 08:19 UTC, phipsae commented on packages/nextjs/app/builders/0xd1B41bE30F980315b8A6b754754aAa299C7abea2/page.tsx
> +                  <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 9
You might want to consider moving the SVG paths into external constants. This would make your code cleaner and more readable

2024-08-13 14:23 UTC, RafaelCaso commented
I've made the requested changes. The 'general advice' is extremely appreciated! In the future I will create and checkout a new branch, push to my forked copy, and then create a PR. Let me know if you'd prefer me to do this now and I will close this PR

2024-08-14 17:59 UTC, phipsae requested changes
Thanks for the changes, looks great! 

I only encountered a little error that is easy to fix, see below.
And no worries with a new PR, only for the next time.

2024-08-14 17:59 UTC, phipsae commented on packages/nextjs/app/builders/0xd1B41bE30F980315b8A6b754754aAa299C7abea2/profileLinks.tsx
> +    stroke-width="0"
I encountered an error that said, "Warning: Invalid DOM property stroke-width. Did you mean strokeWidth?" Replacing stroke-width (for LinkedIn, Youtube, Github) with strokeWidth resolves the issue.

2024-08-14 20:08 UTC, RafaelCaso commented
Oops, that was silly of me. I went and changed stroke-width to strokeWidth for LinkedIn, YouTube, and GitHub.

2024-08-16 12:05 UTC, phipsae commented
Thanks! Looks very nice :) .. and merged

2024-08-16 12:05 UTC, merged