Implementation of issue number 6
BuidlGuidl/batch8.buidlguidl.com pull request #27
Opened 2024-08-21 15:22 UTC by ruhneb2004

## Description

Added a batch member logo on the left hand side of the footer, this will only appear if they are in the allowList. There is also a button on the right side of showing whether they have done the check In or not. If they have then on clicking the button they can see a alert showing the contract address they have deployed. If not then on click they will be redirected to the issue #10.

<img width="1680" alt="Screenshot 2024-08-21 at 8 39 34 PM" src="https://github.com/user-attachments/assets/e490e1ab-96fc-4f9b-b865-6a6d43033600">

<img width="1680" alt="Screenshot 2024-08-21 at 8 46 47 PM" src="https://github.com/user-attachments/assets/c39918cd-15e1-4824-be1a-4518a5efb5e5">

<img width="1680" alt="Screenshot 2024-08-21 at 8 41 30 PM" src="https://github.com/user-attachments/assets/4703deb3-2ddf-494e-8bf1-8e08e47198f7">

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{10}_

Your ENS/address: 0xBC428Bb80B1cc3C29164820528819Abf6b20cB88

2024-08-21 22:43 UTC, derrekcoleman commented
This is a visually lovely PR, @ruhneb2004! I love the footer idea so they can see the custom state on every page!

I suggest you change your message that currently uses the browser's native alert window to something with prettier UI and smoother UX, such as [Daisy UI's modal component](https://daisyui.com/components/modal/). Then you can provide the link to the check-in issue as a link or a button, whatever you think makes more sense.

Make sure to rebase on recent commits to `main` to avoid the Lint errors that have been fixed, too.

2024-08-22 13:39 UTC, ruhneb2004 commented
The above commit was not intended. I am really new to github and it's workflows. Sorry!

2024-08-22 15:43 UTC, ruhneb2004 commented
Changed the alert component to the daisy ui modal component. The ones who have checkedIn can now see their contract in etherscan.io and the ones who have not done the challenge can no visit the issue#10 by clicking the link.

## the ones who have checkedIn
<img width="1680" alt="Screenshot 2024-08-22 at 9 11 52 PM" src="https://github.com/user-attachments/assets/4b968f1d-89f1-4a91-bdec-49dbad776bad">

## the ones who have not checkedIn
<img width="1680" alt="Screenshot 2024-08-22 at 9 12 47 PM" src="https://github.com/user-attachments/assets/abf7adfa-7cd8-4bcf-b37c-d0d5d36ef41e">

Everything else is same!

2024-08-23 17:02 UTC, derrekcoleman commented
> The above commit was not intended. I am really new to github and it's workings. Sorry!

Totally okay! Learning how to use `git rebase` to "cherry pick" which commits you want to keep is exactly what we're here to practice 🥷 

Your updates are looking really nice, @ruhneb2004! Do you want to push it one step further by playing with the styling of the modal so the buttons are more centered and spaced within the width of the container?

2024-08-23 17:25 UTC, ruhneb2004 commented
The github is somewhat making sense now, I have done some little projects and stuff but I haven't done this sort of stuff before, so this is really a cool learning experience.

And for the modal, I would love to give it an another try

2024-08-24 08:00 UTC, ruhneb2004 commented
I have adjusted the spacing of the buttons and some padding for the text as shown below for the modal

<img width="1680" alt="Screenshot 2024-08-24 at 1 25 00 PM" src="https://github.com/user-attachments/assets/a933e6e4-2ae7-4beb-996a-6b02bd27fd5d">

<img width="1680" alt="Screenshot 2024-08-24 at 1 28 33 PM" src="https://github.com/user-attachments/assets/6a29252c-3bd9-49cf-a3f7-e6b6076962c8">


Earlier the styling was not adjusted to the light mode and the text inside the logo was not visible for the batch member logo in the light mode, I have also fixed those issues.

<img width="1680" alt="Screenshot 2024-08-24 at 1 26 36 PM" src="https://github.com/user-attachments/assets/b7f874a6-f220-454f-b49d-3ade09d1f53d">

<img width="1680" alt="Screenshot 2024-08-24 at 1 29 19 PM" src="https://github.com/user-attachments/assets/6f6ca815-80e0-440e-adc1-faf611383d32">

### Todo
After the list of the batch members are out to display I am thinking about making the batch member logo point to our list of the builders

2024-08-26 17:15 UTC, derrekcoleman requested changes
Loving the updated styling on the modal! 🤩 

The last step is to learn how to remove the accidental commits from this pull request before I merge. I had to do the same thing recently and found [this Stack Overflow answer](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-a-pull-request) very useful. `git` can be scary, but visual tools like VS Code's interactive rebase make it easier to choose which commits to keep and which to drop!

Try it out and let us know how it goes 💪

2024-08-26 19:28 UTC, ruhneb2004 commented
Learned something new today! I have removed all the previous commits and added just the ones required. I hope this is what you were looking for @derrekcoleman 😄

2024-08-26 20:17 UTC, ruhneb2004 commented
I learned something new today! I have removed all other commits apart from the one related to this issue. I hope this is what you were looking for 🤞

2024-08-26 20:24 UTC, merged

2024-08-26 20:24 UTC, derrekcoleman commented
Great job, @ruhneb2004! Your git-fu has become stronger today 🥷

2024-08-26 21:44 UTC, ruhneb2004 commented
Haha! Thanks 😊