Fix #21 - Add Padding and icons
BuidlGuidl/batch8.buidlguidl.com pull request #28
Opened 2024-08-23 01:53 UTC by NightmareFox12

#21 

- Removed local icons
- changed the name of the components folder to _components
- add padding in small screens

2024-08-23 19:22 UTC, phipsae requested changes
Thanks, @NightmareFox12, for this PR! The code is very neat and clear.

I just have a small comment.

As general advice for future PRs, please make sure to create and check out a new branch. Also, consider providing a more detailed description. You can refer to Zak's contribution guidelines here: https://gist.github.com/ZakGriffith/69d1eb8baebddd7d370b87a65a7e3ec0.

2024-08-23 19:22 UTC, phipsae commented on packages/nextjs/app/builders/0xD2692F9df925D18D527ABe8b3d99EE9E9C8d75AE/_components/SkillComponent.tsx
> +import React from "react";
If you're using Next.js, you no longer need to import React manually, as Next.js automatically includes it for you

2024-08-27 16:31 UTC, phipsae commented on packages/nextjs/app/builders/0xD2692F9df925D18D527ABe8b3d99EE9E9C8d75AE/_components/SkillComponent.tsx
> +import React from "react";
@NightmareFox12 don't forget to push the changes :)

2024-08-28 13:54 UTC, Pabl0cks approved these changes
Thanks for the updates @NightmareFox12 !! Looking good to me 🙌

2024-08-30 23:28 UTC, NightmareFox12 commented on packages/nextjs/app/builders/0xD2692F9df925D18D527ABe8b3d99EE9E9C8d75AE/page.tsx
> +              src={nightmareFoxImage}
done ! ✨

2024-10-27 21:04 UTC, closed without merging